name: Appwrite Keep Alive

on:
  schedule:
    # This runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Appwrite API
        run: |
          curl -X GET "${{ secrets.APPWRITE_ENDPOINT }}/health" \
          -H "X-Appwrite-Project: ${{ secrets.APPWRITE_PROJECT_ID }}"
